[package]
name = "vdom_macro"
version = "0.0.0"
authors = ["Thomas Heck <t@b128.net>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.8"

[dependencies.syn]
version = "0.15.14"
features = ["extra-traits"]
